### PR TITLE
Fix call to reproject_interp

### PR DESCRIPTION
**Pull request by e-koch**
`shape_out` has its own kwarg.

### CODE REVIEW

**Comment by keflavich** [comment]
@e-koch any tests you want to add?  This function is not tested at all now.

**Comment by e-koch** [comment]
@keflavich It couldn't handle the cube reprojection I need to do right now (way too big), so I haven't actually used it yet. I'll add an issue to remind me later.

**Comment by keflavich** [comment]
@e-koch OK.  If you're having trouble with really large cubes, it might be worth trying to re-make the iterator with a write-to-disk at each step.  I've recently had to do this for some files, and I ended up using astropy.io.fits directly instead of spectral-cube.  It would be better if we could make SC work with this.

The approach we'll need to take is to open the file with mode='update' (which I hope can work on arbitrarily large files....) and then edit each frame in turn.  It may require specifying both an input & an output file on disk, which is somewhat contrary to the general approach of spectral-cube, but is necessary for this sort of operation.   Now that I think of it, having a general mechanism for streaming from one file to another seems like a killer app for SC.

**Comment by e-koch** [comment]
Agreed. That's basically what I've been having to do with large manipulations on big cubes. I'm up for adding this in, but it'll be a few weeks before I can get to it.

**Pull request merged**
