### PR TITLE
Pass `self.allow_huge_operations` to convolve_fft`

### PR DESCRIPTION
**Pull request by keflavich**
Solves issue #696 

`astropy.convolution.convolve` doesn't accept `allow_huge`, so we have to check which function we're calling before deciding what to pass.

### CODE REVIEW

**Review by e-koch — CHANGES_REQUESTED** [review]
Looks good. It's unclear to me where the test failures are coming from, though. I ran locally and it seemed to be fine.

The only change is to take the `if` statements out of `convfunc`. It should be fine outside of the function and avoids an extra if call in the wrapper.

**Comment by keflavich** [comment]
I don't think we can take the `if` statement out of the `convfunc` because of the possibility of `allow_huge` being passed via `apply_function_parallel_*` as noted in https://github.com/radio-astro-tools/spectral-cube/pull/631

**Comment by e-koch** [comment]
Good point! That makes sense.

**Review by e-koch — DISMISSED** [review]

**Comment by keflavich** [comment]
I definitely wouldn't have caught that except for the comment one of us left a while back.

But I would like to get tests passing before merging.

**Comment by e-koch** [comment]
Issue is in `test_beams_convolution`. For some reason, the fixture isn't getting read in or something? See line 64991 in the build log.

**Comment by e-koch** [comment]
Issue is in `test_beams_convolution`. For some reason, the fixture isn't getting read in or something? See line 64991 in the build log.

**Comment by keflavich** [comment]
Let's try to figure this out on next week's telecon

**Comment by keflavich** [comment]
I'm skeptical of this build failure.  It seems to be saying that just passing along some kwargs here is making all the open-files tests fail.  No way.

**Comment by e-koch** [comment]
Somehow it's a file being left open. Removing `--open-files` from the pytest call fixes things. I suspect the memory map file, though it's not a problem elsewhere?

**Comment by e-koch** [comment]
Most of these failure are new, though they all happen at the same place. Before only `py39-novis-cov` failed in this way.

**Comment by e-koch** [comment]
I'm still unsure _what_ the failure is caused by but it's triggered by accessing `self.allow_huge_operations` within the convolution wrapper. For example, directly setting a boolean works in my local tests:
```
        def convfunc(img, **kwargs):
            if convolve is convolution.convolve_fft and 'allow_huge' not in kwargs:
                kwargs['allow_huge'] = True
            return convolve(img, kernel, normalize_kernel=True, **kwargs).reshape(img.shape) * beam_ratio_factor
```
So this must be some weird interaction of accessing `self` from within this wrapper, which gets passed to `SpectralCube.apply_function_parallel_spatial`.

I'm fairly sure we can just move the if statement outside of the wrapper to avoid this (?)

**Comment by e-koch** [comment]
@keflavich  I tested this locally on a >1 GB cube. ``allow_huge`` was passed.

It would be great to test this but we only trigger the `allow_huge` flag for >1 GB sizes in convolve_fft.

**Comment by keflavich** [comment]
We could make the threshold configurable (is it already configurable?) and set the threshold lower for tests

**Comment by keflavich** [comment]
Oh, wow, I bet the `convfunc` is getting pickled (or in some way stored), which is putting `self` (which is the cube) into memory.  That's... not an interaction I would've predicted.

**Comment by keflavich** [comment]
Should we try to add another test, or just merge this?  I'll leave it to you

**Comment by e-koch** [comment]
I don't see an easy way to trigger the `allow_huge` flag in `convolve_fft`. Neither threshold is configurable :`convolve_fft` is 1 GB fixed, same with the `is_huge` check here https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/cube_utils.py#L257).

For now, I've added a bool flag to turn enable `allow_huge_operations` in a couple of the convolution tests. I'll check our list of issues and add a note to return to this when the threshold is configurable.

One of us can merge once the tests pass.

**Comment by keflavich** [comment]
yeah, we could make https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/cube_utils.py#L255 configurable for testing at least.  But we can do that somewhere else.

**Pull request merged**
