### PR TITLE
Fix to_glue with recent versions of glue

### PR DESCRIPTION
**Pull request by astrofrog**
I've also changed some of the tests to use importorskip to simplify skipping related to whether a package is present. There's some more cleanup I'd like to do but I'll open a separate PR for that.

Fixes https://github.com/radio-astro-tools/spectral-cube/issues/163

### CODE REVIEW

**Comment by astrofrog** [comment]
I'm investigating the test failure

**Comment by astrofrog** [comment]
I'll try and fix pvextractor so it works with Matplotlib 2.x - I probably won't be able to do this for another week though.

**Comment by astrofrog** [comment]
The test failure will be fixed once https://github.com/radio-astro-tools/pvextractor/pull/89 is merged

**Comment by keflavich** [comment]
Failures are related to the pvextractor GUI.  Either skip those tests or fix it? =)

**Comment by astrofrog** [comment]
@keflavich - I fixed the pvextractor in PR https://github.com/radio-astro-tools/pvextractor/pull/89 - can you review that?

**Comment by keflavich** [comment]
Yep, my bad forgetting that one.  I'll re-run travis here...

**Comment by astrofrog** [comment]
@keflavich - thanks! looks like it worked :)

**Pull request merged**
