### PR TITLE
bottleneck.nanmedian does not allow axis with a tuple/list.

### LINKED ISSUE #476: `bottleneck.nanmedian` does not allow axis to have a tuple/list
The current version of `bottleneck.nanmedian` (v1.2.1) doesn't allow axis to have a tuple/list, for example:
```
import numpy as np
import bottleneck as bnok

A = np.random.normal(0, 100, (20, 20, 500))

print(np.nanmedian(A, axis=(1, 2)))
print(bnok.nanmedian(A, axis=(1, 2)))
```

This produces an error:
```
TypeError: `axis` must be an integer or None
```

Then, if bottleneck is in the environment I get fails in the `cube.median()` code if I pass in axis as a list or tuple. 

I have a fix and will create a PR.

### PR DESCRIPTION
**Pull request by brechmos-stsci**
As stated, as of version 1.2.1 of bottleneck it does not allow a tuple/list for the axis.  So, this adds a check to see if that is the case.

Fixes #476

### CODE REVIEW

**Comment by brechmos-stsci** [comment]
@keflavich If you are good with this fix, it would be great to commit (fixes some spectral stuff I am working on). If you have a better suggestion for a fix, please feel free to post and I'll correct.

**Comment by keflavich** [comment]
Looks good, thanks for the catch.  It's annoying that they don't support something so basic.

Could you add a test that catches this?

**Comment by brechmos-stsci** [comment]
@keflavich I added the test and seems to have passed (wahoo!).

**Comment by keflavich** [comment]
@astrofrog has a workaround:
https://github.com/glue-viz/glue/pull/1641/files#diff-4e6dc6cf25762999955424dd2d995973R300

**Pull request merged**
