### PR TITLE
metadata persists to new SpectralCube?

### PR DESCRIPTION
**Pull request by keflavich**
If I read in a cube and look at the metadata:

```
 cube = SpectralCube.read('VLA_Data/AT0206/imaging/M33_206_b_c_HI.fits')
cube._meta
# {'BUNIT': 'Jy/beam',
 'beam': Beam: BMAJ=6.354 arcsec BMIN=5.86296 arcsec BPA=87.9 deg}
```
and then read in another cube:
```
cube_2 = SpectralCube.read('Arecibo/M33only.fits')
cube_2._meta
# {'BUNIT': 'K',
 'beam': Beam: BMAJ=227.99988 arcsec BMIN=198.0 arcsec BPA=0.0 deg}
```
the metadata in ```cube``` is now the metadata of ```cube_2```:
```
cube._meta
# {'BUNIT': 'K',
 'beam': Beam: BMAJ=227.99988 arcsec BMIN=198.0 arcsec BPA=0.0 deg}
```

Is this related to issues with caching (#204)?

### CODE REVIEW

**Comment by keflavich** [comment]
this may have revealed a severe problem with our tests, or my solution may have broken things worse - apparently the tests now lack brightness units in many cases

**Comment by e-koch** [comment]
The ```moment_cube``` in the tests doesn't have a unit:
```    hdu = fits.PrimaryHDU(data=cube*u.K, header=wcs.to_header())```

That fixes all but 3 of the tests.

**Comment by e-koch** [comment]
```wcs.to_header()``` has not ```BUNIT```. This fixes the all the units issues.

```
def moment_cube():
    cube = np.arange(27).reshape([3, 3, 3]).astype(np.float)
    wcs = WCS(naxis=3)
    wcs.wcs.ctype = ['RA---TAN', 'DEC--TAN', 'VELO']
    # choose values to minimize spherical distortions
    wcs.wcs.cdelt = np.array([-1, 2, 3], dtype='float32') / 1e5
    wcs.wcs.crpix = np.array([1, 1, 1], dtype='float32')
    wcs.wcs.crval = np.array([0, 1e-3, 2e-3], dtype='float32')
    wcs.wcs.cunit = ['deg', 'deg', 'km/s']

    header = wcs.to_header()
    header['BUNIT'] = 'K'

    hdu = fits.PrimaryHDU(data=cube, header=header)
    return hdu
```

**Comment by keflavich** [comment]
@e-koch could you PR that onto mine?

**Comment by e-koch** [comment]
Yup. One sec

**Comment by e-koch** [comment]
@keflavich - Made PR to here

**Pull request merged**
