### PR TITLE
Fix warnings when a beam is not defined

### PR DESCRIPTION
**Pull request by e-koch**
Addresses #560. 

Changes the behaviour such that `SpectralCube.beam` raises a `NoBeamError` if a beam object is not defined. Removes the UserWarning in 560 that wasn't very helpful/informative.

### CODE REVIEW

**Comment by keflavich** [comment]
There are failures that are not doc failures but might be numpy version failures?  I'm uncomfortable with these precision-related errors; I don't know why they're appearing now.  However, they are below the precision of the methods we're testing, so I guess we push on?  I'm still going to wait a little..

**Comment by e-koch** [comment]
That's worrying. I'll dig a little bit into that precision error.

**Comment by e-koch** [comment]
Ok, I can reproduce this locally on the astropy dev branch ('4.0.dev25484').

**Comment by e-koch** [comment]
@keflavich -- The unit values `cube.jtok_factors` was tested against had what I think was small rounding errors.

**Comment by e-koch** [comment]
Also, `radio-beam`'s tests are fine w/ astropy v4dev

**Comment by keflavich** [comment]
👍 could you rebase this now that #588 is done?

**Comment by keflavich** [comment]
@e-koch could you rebase this again?  It looks like there are  40 commits but should only be ~8?

**Comment by e-koch** [comment]
So the rebase said it went fine... but clearly it hasn't

**Comment by e-koch** [comment]
Ok. Merging worked. _Should_ be ready if this passes.

**Pull request merged**
