### PR TITLE
Enable CASA tests

### PR DESCRIPTION
**Pull request by keflavich**
I want travis to run CASA tests.  They fail, though, because CASA doesn't install the right version of numpy.  See https://github.com/radio-astro-tools/spectral-cube/pull/300

### CODE REVIEW

**Comment by keflavich** [comment]
Current difficulty is sorting out why hashlib doesn't import well on casa on travis.

It exists at these locations:
```
/home/travis/build/radio-astro-tools/spectral-cube/casa-release-4.7.2-el6/lib/python2.7/lib-dynload/_hashlib.so
/home/travis/build/radio-astro-tools/spectral-cube/casa-release-4.7.2-el6/etc/carta/lib/python2.7/lib-dynload/_hashlib.so
/home/travis/miniconda/pkgs/python-2.7.13-0/lib/python2.7/lib-dynload/_hashlib.so
/home/travis/miniconda/envs/test/lib/python2.7/lib-dynload/_hashlib.so
/opt/python/2.6.9/lib/python2.6/lib-dynload/_hashlib.so
/opt/python/2.7.9/lib/python2.7/lib-dynload/_hashlib.so
```

So maybe overwriting the non-Carta version would make it work?

@low-sky is this the sort of thing anyone on your team might have some knowledge about?

**Comment by keflavich** [comment]
The failure is related to hashlib, but not at import time:
https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/227480570#L674

**Comment by low-sky** [comment]
Maybe.  Our build manager may have some insight here, but do you know which copy of the hashlib it's linking to?  

This line appears to succeed which is puzzling:

```
if [[ $CASA_BIN ]]; then ${CASA_CONFIG} --exec python -c "from hashlib import md5, sha1, sha256"; fi
```

**Comment by keflavich** [comment]
No, I haven't figured out which version it's linked to, but the previous line:
```
/home/travis/build/radio-astro-tools/spectral-cube/casa-release-4.7.2-el6/lib/python2.7/hashlib.pyc
```
at least gives us the path.

**Comment by keflavich** [comment]
CASA's hashlib *does* work now.  Apparently the problem was that travis is running RH6 and not RH7.

Now the issue is that the wrong numpy is being used when importing astropy.

**Comment by keflavich** [comment]
Getting close?

https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/227693543

This error confuses me:
```
$ if [[ $SETUP_CMD != egg_info ]]; then cd spectral_cube/tests/data ; make ; cd ../../../; fi
python make_test_cubes.py
Traceback (most recent call last):
  File "make_test_cubes.py", line 6, in <module>
    from astropy.io import fits
  File "/home/travis/.local/lib/python2.7/site-packages/astropy/__init__.py", line 116, in <module>
    _check_numpy()
  File "/home/travis/.local/lib/python2.7/site-packages/astropy/__init__.py", line 100, in _check_numpy
    import numpy
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/core/__init__.py", line 72, in <module>
    from numpy.testing.nosetester import _numpy_tester
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/testing/__init__.py", line 12, in <module>
    from . import decorators as dec
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/testing/decorators.py", line 20, in <module>
    from .utils import SkipTest, assert_warns
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp, mkstemp
  File "/home/travis/miniconda/envs/test/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
  File "/home/travis/.local/lib/python2.7/site-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
  File "numpy.pxd", line 86, in init mtrand (numpy/random/mtrand/mtrand.c:42488)
AttributeError: 'module' object has no attribute 'dtype'
make: *** [advs.fits] Error 1
```
because it is apparently failing at the FITS import stage even though `import astropy.io.fits` worked previously.

But, that said, my `PYTHONPATH` was wrong and it looks like CASA is never installing anything to `~/.casa/lib/python2.7/site-packages` as I had previously assumed.

**Comment by keflavich** [comment]
@astrofrog do you have any recollection of how CASA chooses its path order?  I'm still unable to make CASA import a more modern numpy (https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/227710180#L647), which is necessary for spectral-cube because it relies on np >= 1.8

**Comment by keflavich** [comment]
The problem is that `casa-config` overwrites the `PYTHONPATH`.  Maybe the only option is to hack it...?

**Comment by keflavich** [comment]
Heeeeey nice I almost got it!

https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/228120920#L803

**Comment by keflavich** [comment]
Hey neat, it worked, all you have to do is make empty ipyrc files.

Currently running (...probably into the ground):
https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/228913960

**Comment by keflavich** [comment]
New set of problems:
https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/228938133

 * We are green even though the tests are failing.  [This line](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/228938133#L1001) explicitly means the tests have failed, yet [this line](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/228938133#L1006) says we succeeded
 * [the only tests we care about](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/228938133#L896) are being skipped even though [they absolutely should not be](https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/228938133#L774)

**Comment by astrofrog** [comment]
@keflavich - I think it would be cleaner to actually do a lot of the CASA setup and patching in a docker image then just set up CircleCI here and run the tests in the docker image.

**Comment by keflavich** [comment]
Probably superceded by #458

**Pull request closed without merging**
