### PR TITLE
Fixed Valid Stokes List in Stokes Cube to allow for all possible Stokes values.

### PR DESCRIPTION
**Pull request by preshanth**
The list is based on the Stokes enum in the casacore c++ of all the different types of Stokes variants that are possible.

### CODE REVIEW

**Review by keflavich — APPROVED** [review]

**Comment by keflavich** [comment]
@preshanth could you help us come up with tests for this?  We can just make some artificial cubes with these various stokes properties.

**Comment by preshanth** [comment]
Surething @keflavich. I have to come with some sane ones for a couple of the weird edge cases of mixed polarizations so let me think it over properly.

**Comment by preshanth** [comment]
I have put in tests to check for and allow the passing of all stokes values given till now. This is okay for now. I have not yet figured out how to distnguish between voltage and power values in this setup.

**Review by keflavich — APPROVED** [review]

**Comment by keflavich** [comment]
@e-koch want to give this a last look and then merge if you agree?

**Review by e-koch — APPROVED** [review]

**Pull request merged**
