### PR TITLE
CLASS LMV reader

### PR DESCRIPTION
**Pull request by keflavich**
This is a reader for GILDAS-CLASS LMV cubes.  They are nearly identical to FITS cubes, just laid out in such a way that they have to be read differently.

I have no plans to write a writer for this format.

I have virtually no test data available for it either, but I'll try to generate some.

### CODE REVIEW

**Comment by keflavich** [comment]
@vilhelmp - could you make the cube even smaller, e.g. cut it down to a 4x4x4 cube or something tiny like that?  And could you also provide a FITS version?  I'm working on debugging & setting up a genuine test suite, but I still don't have access to a functioning CLASS program (because of gtk).

**Comment by vilhelmp** [comment]
@keflavich OK, let me know if this works: http://strw.leidenuniv.nl/~persson/example_cube.lmv

**Comment by keflavich** [comment]
@vilhelmp that's the size I'm looking for, thanks!  Could you send the FITS-exported version too?  Then I can perform direct keyword-to-keyword comparisons to make sure I didn't miss anything.

**Comment by vilhelmp** [comment]
@keflavich oh, I forgot. its here http://strw.leidenuniv.nl/~persson/example_cube.fits

**Comment by keflavich** [comment]
Thanks @vilhelmp.  I've found a bug already - looks like all my testing was on v2 files but you've given me a v1 file to work with.  Should get interesting...

**Pull request merged**
