### PR TITLE
Fixed Sphinx warnings and enabled nitpicky mode

### PR DESCRIPTION
**Pull request by astrofrog**
@bsipocz - this might bring back memories ;) I was thinking we should probably add the nitpicky option by default to the package-template to encourage good practices? (also with the chunk of code to read in a potential nitpick-exceptions file if present?)

This fixes https://github.com/radio-astro-tools/spectral-cube/issues/338

Note that rather than add ``BaseSpectralCube`` to the API, which I think would be confusing for users, I added the option to add inherited methods to the SpectralCube class (and other top-level objects). This means we can't import Projection and Slice into the top-level at the moment since they inherit Quantity, and that causes a number of issues, so best leave it as-is for now.

### CODE REVIEW

**Comment by bsipocz** [comment]
@astrofrog - There is already an open PR for it in package-template, https://github.com/astropy/package-template/pull/181 ;) (although it's all commented out atm).

**Comment by astrofrog** [comment]
@keflavich - is the yt test failure known?

**Comment by keflavich** [comment]
yes: https://github.com/radio-astro-tools/spectral-cube/issues/335

**Comment by astrofrog** [comment]
@keflavich - ok, then this can be merged

**Pull request merged**
