### PR TITLE
Progressbar: switch to tqdm, add description

### PR DESCRIPTION
**Pull request by keflavich**
As in the title: there are a lot of progressbars scattered throughout spectral-cube, and it can be tricky to track down where they are.  Adding labels should help.

### CODE REVIEW

**Review by astrofrog — CHANGES_REQUESTED** [review]
Looks good to me, but can't we just require tqdm as a dependency as it's so lightweight? This will then simplify the code in utils.py and fix the CI.

**Comment by keflavich** [comment]
I'm OK with that.  @e-koch, you good with just making tqdm a requirement?

**Comment by e-koch** [comment]
agreed. as Tom points out, it's lightweight and simplifies things.

**Comment by keflavich** [comment]
I've added tqdm as a dependency and refactored to use it - but the usage of progressbars is still a little non-tqdm-like.

**Comment by e-koch** [comment]
@keflavich can we close this now that #923 is merged?

**Comment by keflavich** [comment]
Yep.

**Pull request closed without merging**
