### PR TITLE
CASA chunk-based reading fixes

### PR DESCRIPTION
**Pull request by keflavich**
PR #592 was riddled with errors we totally missed because our casa image test coverage is nonexistent.  This will eventually fix that...

### CODE REVIEW

**Comment by keflavich** [comment]
Locally, tests fail with `E                                              OSError: [Errno 24] Too many open files`.  Something is being left open and I can't figure out what

**Comment by keflavich** [comment]
This could use some testing.  I can't run the tests to completion locally because I get the error `E       OSError: [Errno 24] Too many open files`, which is a LIE!  (or, it's truth, and CASA literally cannot close filehandles).

**Comment by keflavich** [comment]
Tests pass locally; the build failures are installation failures in pvextractor.  Maybe there's some astropy-helpers-related incompatibility?

I have an open conversation w/Dave Mehringer started about the problems with `ia.open` performance; he stated that it should only be instantiating a c++ object, not passing over the data, therefore the long load times are not expected and likely indicate some sort of error.

**Comment by keflavich** [comment]
The reader is presently giving me all kinds of super interesting tracebacks that almost certainly have to do with the creation/destruction of SWIG objects:
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-acda8bf7ee9d> in <module>
      2 app = gj.jglue()
      3 from glue.plugins.data_factories.spectral_cube.spectral_cube import read_spectral_cube, spectral_cube_to_data
----> 4 data = spectral_cube_to_data(StokesSpectralCube({'I':cube}))
      5 app.add_data(data)

/orange/adamginsburg/repos/glue/glue/plugins/data_factories/spectral_cube/spectral_cube.py in spectral_cube_to_data(cube, label)
     38 
     39     for component in cube.components:
---> 40         data = getattr(cube, component).unmasked_data[...]
     41         result.add_component(data, label='STOKES {0}'.format(component))
     42 

/orange/adamginsburg/repos/spectral-cube/spectral_cube/cube_utils.py in __getitem__(self, view)
    221 
    222     def __getitem__(self, view):
--> 223         return self._func(self._other, view)
    224 
    225     def __iter__(self):

/orange/adamginsburg/repos/spectral-cube/spectral_cube/spectral_cube.py in unmasked_data(self, view)
   1310             The unmasked data
   1311         """
-> 1312         return u.Quantity(self._data[view], self.unit, copy=False)
   1313 
   1314     def unmasked_copy(self):

/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/units/quantity.py in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    367 
    368         value = np.array(value, dtype=dtype, copy=copy, order=order,
--> 369                          subok=False, ndmin=ndmin)
    370 
    371         # check that array contains numbers or long int objects

~/.local/lib/python3.6/site-packages/dask/array/core.py in __array__(self, dtype, **kwargs)
   1249 
   1250     def __array__(self, dtype=None, **kwargs):
-> 1251         x = self.compute()
   1252         if dtype and x.dtype != dtype:
   1253             x = x.astype(dtype)

~/.local/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

~/.local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

~/.local/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     80         get_id=_thread_get_id,
     81         pack_exception=pack_exception,
---> 82         **kwargs
     83     )
     84 

~/.local/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    489                         _execute_task(task, data)  # Re-execute locally
    490                     else:
--> 491                         raise_exception(exc, tb)
    492                 res, worker_id = loads(res_info)
    493                 state["cache"][key] = res

~/.local/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    128         if exc.__traceback__ is not tb:
    129             raise exc.with_traceback(tb)
--> 130         raise exc
    131 
    132     import pickle as cPickle

~/.local/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    231     try:
    232         task, data = loads(task_info)
--> 233         result = _execute_task(task, data)
    234         id = get_id()
    235         result = dumps((result, id))

~/.local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/.local/lib/python3.6/site-packages/dask/array/core.py in getter(a, b, asarray, lock)
     95         lock.acquire()
     96     try:
---> 97         c = a[b]
     98         if asarray:
     99             c = np.asarray(c)

/orange/adamginsburg/repos/spectral-cube/spectral_cube/io/casa_image.py in __getitem__(self, value)
    155 
    156         log.debug(f'blc={blc}, trc={trc}, inc={inc}, kwargs={self.ia_kwargs}')
--> 157         data = ia.getchunk(blc=blc, trc=trc, inc=inc, **self.ia_kwargs)
    158         ia.done()
    159         ia.close()

~/.local/lib/python3.6/site-packages/casatools/image.py in getchunk(self, blc, trc, inc, axes, list, dropdeg, getmask)
   2142         doc = {'blc': blc, 'trc': trc, 'inc': inc, 'axes': axes, 'list': list, 'dropdeg': dropdeg, 'getmask': getmask}
   2143         assert _pc.validate(doc,schema), str(_pc.errors)
-> 2144         _getchunk_result = _any_dc(self._swigobj.getchunk(_pc.document['blc'], _pc.document['trc'], _pc.document['inc'], _pc.document['axes'], _pc.document['list'], _pc.document['dropdeg'], _pc.document['getmask']))
   2145         return _getchunk_result
   2146 

KeyError: 'blc'
```

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-7-acda8bf7ee9d> in <module>
      2 app = gj.jglue()
      3 from glue.plugins.data_factories.spectral_cube.spectral_cube import read_spectral_cube, spectral_cube_to_data
----> 4 data = spectral_cube_to_data(StokesSpectralCube({'I':cube}))
      5 app.add_data(data)

/orange/adamginsburg/repos/glue/glue/plugins/data_factories/spectral_cube/spectral_cube.py in spectral_cube_to_data(cube, label)
     38 
     39     for component in cube.components:
---> 40         data = getattr(cube, component).unmasked_data[...]
     41         result.add_component(data, label='STOKES {0}'.format(component))
     42 

/orange/adamginsburg/repos/spectral-cube/spectral_cube/cube_utils.py in __getitem__(self, view)
    221 
    222     def __getitem__(self, view):
--> 223         return self._func(self._other, view)
    224 
    225     def __iter__(self):

/orange/adamginsburg/repos/spectral-cube/spectral_cube/spectral_cube.py in unmasked_data(self, view)
   1310             The unmasked data
   1311         """
-> 1312         return u.Quantity(self._data[view], self.unit, copy=False)
   1313 
   1314     def unmasked_copy(self):

/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/units/quantity.py in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    367 
    368         value = np.array(value, dtype=dtype, copy=copy, order=order,
--> 369                          subok=False, ndmin=ndmin)
    370 
    371         # check that array contains numbers or long int objects

~/.local/lib/python3.6/site-packages/dask/array/core.py in __array__(self, dtype, **kwargs)
   1249 
   1250     def __array__(self, dtype=None, **kwargs):
-> 1251         x = self.compute()
   1252         if dtype and x.dtype != dtype:
   1253             x = x.astype(dtype)

~/.local/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

~/.local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

~/.local/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     80         get_id=_thread_get_id,
     81         pack_exception=pack_exception,
---> 82         **kwargs
     83     )
     84 

~/.local/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    489                         _execute_task(task, data)  # Re-execute locally
    490                     else:
--> 491                         raise_exception(exc, tb)
    492                 res, worker_id = loads(res_info)
    493                 state["cache"][key] = res

~/.local/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    128         if exc.__traceback__ is not tb:
    129             raise exc.with_traceback(tb)
--> 130         raise exc
    131 
    132     import pickle as cPickle

~/.local/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    231     try:
    232         task, data = loads(task_info)
--> 233         result = _execute_task(task, data)
    234         id = get_id()
    235         result = dumps((result, id))

~/.local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/.local/lib/python3.6/site-packages/dask/array/core.py in getter(a, b, asarray, lock)
     95         lock.acquire()
     96     try:
---> 97         c = a[b]
     98         if asarray:
     99             c = np.asarray(c)

/orange/adamginsburg/repos/spectral-cube/spectral_cube/io/casa_image.py in __getitem__(self, value)
    146         # use the ia tool to get the file contents
    147         try:
--> 148             ia.open(self.filename, cache=False)
    149         except AssertionError as ex:
    150             if 'must be of cReqPath type' in str(ex):

~/.local/lib/python3.6/site-packages/casatools/image.py in open(self, infile, cache)
   2891         doc = {'infile': infile, 'cache': cache}
   2892         assert _pc.validate(doc,schema), str(_pc.errors)
-> 2893         _open_result = self._swigobj.open(_str_ec(_pc.document['infile']), _pc.document['cache'])
   2894         return _open_result
   2895 

KeyError: 'infile'
```

etc.  I'm not sure we're ever going to get parallel iatool reads working...

**Comment by keflavich** [comment]
Here's another:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-9-acda8bf7ee9d> in <module>
      2 app = gj.jglue()
      3 from glue.plugins.data_factories.spectral_cube.spectral_cube import read_spectral_cube, spectral_cube_to_data
----> 4 data = spectral_cube_to_data(StokesSpectralCube({'I':cube}))
      5 app.add_data(data)

/orange/adamginsburg/repos/glue/glue/plugins/data_factories/spectral_cube/spectral_cube.py in spectral_cube_to_data(cube, label)
     38 
     39     for component in cube.components:
---> 40         data = getattr(cube, component).unmasked_data[...]
     41         result.add_component(data, label='STOKES {0}'.format(component))
     42 

/orange/adamginsburg/repos/spectral-cube/spectral_cube/cube_utils.py in __getitem__(self, view)
    221 
    222     def __getitem__(self, view):
--> 223         return self._func(self._other, view)
    224 
    225     def __iter__(self):

/orange/adamginsburg/repos/spectral-cube/spectral_cube/spectral_cube.py in unmasked_data(self, view)
   1310             The unmasked data
   1311         """
-> 1312         return u.Quantity(self._data[view], self.unit, copy=False)
   1313 
   1314     def unmasked_copy(self):

/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/units/quantity.py in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    367 
    368         value = np.array(value, dtype=dtype, copy=copy, order=order,
--> 369                          subok=False, ndmin=ndmin)
    370 
    371         # check that array contains numbers or long int objects

~/.local/lib/python3.6/site-packages/dask/array/core.py in __array__(self, dtype, **kwargs)
   1249 
   1250     def __array__(self, dtype=None, **kwargs):
-> 1251         x = self.compute()
   1252         if dtype and x.dtype != dtype:
   1253             x = x.astype(dtype)

~/.local/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    173         dask.base.compute
    174         """
--> 175         (result,) = compute(self, traverse=False, **kwargs)
    176         return result
    177 

~/.local/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    444     keys = [x.__dask_keys__() for x in collections]
    445     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 446     results = schedule(dsk, keys, **kwargs)
    447     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    448 

~/.local/lib/python3.6/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     80         get_id=_thread_get_id,
     81         pack_exception=pack_exception,
---> 82         **kwargs
     83     )
     84 

~/.local/lib/python3.6/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    489                         _execute_task(task, data)  # Re-execute locally
    490                     else:
--> 491                         raise_exception(exc, tb)
    492                 res, worker_id = loads(res_info)
    493                 state["cache"][key] = res

~/.local/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    128         if exc.__traceback__ is not tb:
    129             raise exc.with_traceback(tb)
--> 130         raise exc
    131 
    132     import pickle as cPickle

~/.local/lib/python3.6/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    231     try:
    232         task, data = loads(task_info)
--> 233         result = _execute_task(task, data)
    234         id = get_id()
    235         result = dumps((result, id))

~/.local/lib/python3.6/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

~/.local/lib/python3.6/site-packages/dask/array/core.py in getter(a, b, asarray, lock)
     95         lock.acquire()
     96     try:
---> 97         c = a[b]
     98         if asarray:
     99             c = np.asarray(c)

/orange/adamginsburg/repos/spectral-cube/spectral_cube/io/casa_image.py in __getitem__(self, value)
    155 
    156         log.debug(f'blc={blc}, trc={trc}, inc={inc}, kwargs={self.ia_kwargs}')
--> 157         data = ia.getchunk(blc=blc, trc=trc, inc=inc, **self.ia_kwargs)
    158         ia.done()
    159         ia.close()

~/.local/lib/python3.6/site-packages/casatools/image.py in getchunk(self, blc, trc, inc, axes, list, dropdeg, getmask)
   2141         schema = {'blc': {'type': 'cIntVec', 'coerce': [_coerce.to_list,_coerce.to_intvec]}, 'trc': {'type': 'cIntVec', 'coerce': [_coerce.to_list,_coerce.to_intvec]}, 'inc': {'type': 'cIntVec', 'coerce': [_coerce.to_list,_coerce.to_intvec]}, 'axes': {'type': 'cIntVec', 'coerce': [_coerce.to_list,_coerce.to_intvec]}, 'list': {'type': 'cBool'}, 'dropdeg': {'type': 'cBool'}, 'getmask': {'type': 'cBool'}}
   2142         doc = {'blc': blc, 'trc': trc, 'inc': inc, 'axes': axes, 'list': list, 'dropdeg': dropdeg, 'getmask': getmask}
-> 2143         assert _pc.validate(doc,schema), str(_pc.errors)
   2144         _getchunk_result = _any_dc(self._swigobj.getchunk(_pc.document['blc'], _pc.document['trc'], _pc.document['inc'], _pc.document['axes'], _pc.document['list'], _pc.document['dropdeg'], _pc.document['getmask']))
   2145         return _getchunk_result

AssertionError: {'remove': ['unknown field'], 'verbose': ['unknown field']}
```

**Comment by e-koch** [comment]
I'm getting an AssertionError but from a different place. Here's the traceback in the casa part:
```
~/ownCloud/code_development/radio_astro_tools/spectral-cube/spectral_cube/io/casa_image.py in __getitem__(self, value)
    152                               .format(self.filename, str(ex)))
    153             else:
--> 154                 raise ex
    155
    156         log.debug(f'blc={blc}, trc={trc}, inc={inc}, kwargs={self.ia_kwargs}')

~/ownCloud/code_development/radio_astro_tools/spectral-cube/spectral_cube/io/casa_image.py in __getitem__(self, value)
    146         # use the ia tool to get the file contents
    147         try:
--> 148             ia.open(self.filename, cache=False)
    149         except AssertionError as ex:
    150             if 'must be of cReqPath type' in str(ex):

~/anaconda3/envs/casa_py36/lib/python3.6/site-packages/casatools/image.py in open(self, infile, cache)
   2817         schema = {'infile': {'type': 'cReqPath', 'coerce': _coerce.expand_path}, 'cache': {'type': 'cBool'}}
   2818         doc = {'infile': infile, 'cache': cache}
-> 2819         assert _pc.validate(doc,schema), str(_pc.errors)
   2820         _open_result = self._swigobj.open(_str_ec(_pc.document['infile']), _pc.document['cache'])
   2821         return _open_result

AssertionError: {'cache': ['unknown field']}

``` 

What I don't get is that running this line in the debugger raises no exception.

**Comment by keflavich** [comment]
yeah, exactly!  There is probably some multithread black magic happening behind the scenes

**Comment by keflavich** [comment]
(I also ran in the debugger and also found that this assertion is True)

**Comment by e-koch** [comment]
Funky... So this is some weird interaction of dask and iatool.

**Comment by keflavich** [comment]
Yeah, that's my read.  What version of casatools are you on? I'm on 2019.116, but we're moving to a different versioning system soon.  Could you tell me the results of `%timeit ia.open('big.file.image'); ia.close()`?

**Comment by e-koch** [comment]
Version 6.1.0.17 from `casatools.version_string()`
For a 4.5 GB cube via an NFS mounted disc:
```
24.3 ms ± 2.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by keflavich** [comment]
Upgrading to the latest CASA wheels (but 6.0.0.27) got the `ia.open` times down to 10s of ms for me too now.

**Comment by keflavich** [comment]
Status report:

1. Failures here (on travis) are still related to pvextractor install
2. CASA still does not close files, despite promises to the contrary.  I don't know how to forcibly close them.

**Comment by keflavich** [comment]
Preshanth suggested that destroying the `ia` instance might be needed to force-close the files

**Comment by astrofrog** [comment]
There were three tests for which I couldn't fix the open file handles for now, I've marked these so that the pytest openfiles plugin skips them. In addition for some of the tests I had to explicitly set ``self.c = self.d = None`` - this is because of what I think is a bug in pytest-openfiles, and I'll investigate this later.

**Comment by astrofrog** [comment]
For the record, I found that some of the file handle issues disappeared with CASA when using ``fromarray`` instead of ``newimagefromarray`` - not sure what the internal differences are.

**Comment by astrofrog** [comment]
All CI configurations now include the ``--open-files`` flag, to avoid any regressions in future.

**Comment by keflavich** [comment]
Merging this now, thanks for the fixes @astrofrog.  I will put this into practice shortly, so don't be surprised if I turn up something else broken...

**Pull request merged**
