### PR TITLE
fix parameter syntax error introduced in PR 883

### PR DESCRIPTION
**Pull request by tvwenger**
See https://github.com/radio-astro-tools/spectral-cube/issues/884

### CODE REVIEW

**Comment by keflavich** [comment]
Could you add a test for this?  It's not covered in our current tests.  I can have a look but probably not immediately

**Comment by keflavich** [comment]
Actually our tests do cover this and I merged a red PR.  Bad.

**Comment by tvwenger** [comment]
> Actually our tests do cover this and I merged a red PR. Bad.

No worries, it happens to the all of us!

**Comment by tvwenger** [comment]
I notice that a lot of these tests are failing with errors:

`TypeError: _new_view() got an unexpected keyword argument 'propagate_info'`

Are these expected?

**Comment by keflavich** [comment]
No, they're a consequence of https://github.com/astropy/astropy/pull/14518.  I have a bugfix in progress.

**Comment by keflavich** [comment]
merged in #886

**Pull request closed without merging**
