### PR TITLE
Update travis grid

### PR DESCRIPTION
**Pull request by keflavich**
The travis grid is broken because of astropy updates:

https://travis-ci.org/radio-astro-tools/spectral-cube/builds/563172188

### CODE REVIEW

**Comment by keflavich** [comment]
docs failures: 
https://travis-ci.org/radio-astro-tools/spectral-cube/jobs/563257732

**Comment by keflavich** [comment]
I can't run the tests locally, they freeze somewhere...

**Comment by keflavich** [comment]
none of these messages make sense to me:
```

WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
/home/travis/miniconda/envs/test/lib/python3.6/site-packages/sphinx/util/docutils.py:311: RemovedInSphinx30Warning: function based directive support is now deprecated. Use class based directive instead.
  RemovedInSphinx30Warning)
/home/travis/build/radio-astro-tools/spectral-cube/astropy_helpers/astropy_helpers/sphinx/themes/bootstrap-astropy/layout.html:15: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  <div class="topbar">
/home/travis/build/radio-astro-tools/spectral-cube/docs/accessing.rst:48: WARNING: py:attr reference target not found: spectral_cube.SpectralCube.world
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/lower_dimensional_structures.py:docstring of spectral_cube.OneDSpectrum.shape:24: WARNING: py:obj reference target not found: ndarray.reshape
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/lower_dimensional_structures.py:docstring of spectral_cube.OneDSpectrum.size:17: WARNING: py:obj reference target not found: a.size
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/__init__.py:docstring of spectral_cube.OneDSpectrum.flatten:32: WARNING: py:obj reference target not found: flat
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/lower_dimensional_structures.py:docstring of spectral_cube.Projection.shape:24: WARNING: py:obj reference target not found: ndarray.reshape
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/lower_dimensional_structures.py:docstring of spectral_cube.Projection.size:17: WARNING: py:obj reference target not found: a.size
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/__init__.py:docstring of spectral_cube.Projection.flatten:32: WARNING: py:obj reference target not found: flat
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/base_class.py:docstring of spectral_cube.Projection.world_spines:8: WARNING: py:meth reference target not found: world
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/lower_dimensional_structures.py:docstring of spectral_cube.Slice.shape:24: WARNING: py:obj reference target not found: ndarray.reshape
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/lower_dimensional_structures.py:docstring of spectral_cube.Slice.size:17: WARNING: py:obj reference target not found: a.size
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/__init__.py:docstring of spectral_cube.Slice.flatten:32: WARNING: py:obj reference target not found: flat
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/base_class.py:docstring of spectral_cube.Slice.world_spines:8: WARNING: py:meth reference target not found: world
/home/travis/build/radio-astro-tools/spectral-cube/docs/api/spectral_cube.SpectralCube.rst:71:<autosummary>:1: WARNING: py:obj reference target not found: fill_value
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/base_class.py:docstring of spectral_cube.SpectralCube.with_fill_value:2: WARNING: py:obj reference target not found: fill_value
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/base_class.py:docstring of spectral_cube.SpectralCube.world_spines:8: WARNING: py:meth reference target not found: world
/home/travis/build/radio-astro-tools/spectral-cube/docs/api/spectral_cube.VaryingResolutionSpectralCube.rst:75:<autosummary>:1: WARNING: py:obj reference target not found: fill_value
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/base_class.py:docstring of spectral_cube.VaryingResolutionSpectralCube.with_fill_value:2: WARNING: py:obj reference target not found: fill_value
/home/travis/build/radio-astro-tools/spectral-cube/build/lib.linux-x86_64-3.6/spectral_cube/base_class.py:docstring of spectral_cube.VaryingResolutionSpectralCube.world_spines:8: WARNING: py:meth reference target not found: world
/home/travis/build/radio-astro-tools/spectral-cube/docs/big_data.rst:45: WARNING: py:meth reference target not found: SpectralCube.filled_data
/home/travis/build/radio-astro-tools/spectral-cube/docs/big_data.rst:45: WARNING: py:meth reference target not found: SpectralCube.unmasked_data
/home/travis/build/radio-astro-tools/spectral-cube/docs/big_data.rst:45: WARNING: py:meth reference target not found: SpectralCube.world
/home/travis/build/radio-astro-tools/spectral-cube/docs/big_data.rst:58: WARNING: py:meth reference target not found: SpectralCube.filled_data
/home/travis/build/radio-astro-tools/spectral-cube/docs/big_data.rst:58: WARNING: py:meth reference target not found: SpectralCube.unmasked_data
/home/travis/build/radio-astro-tools/spectral-cube/docs/manipulating.rst:7: WARNING: py:attr reference target not found: spectral_cube.SpectralCube.spectral_axis
/home/travis/build/radio-astro-tools/spectral-cube/docs/masking.rst:67: WARNING: py:attr reference target not found: spectral_cube.SpectralCube.unmasked_data
```

`astropy.extern.six` isn't used anywhere I can see, for starters.  These other attributes... all exist.

**Comment by bsipocz** [comment]
@keflavich - you need to use the full namespace, `~SpectralCube.filled_data` makes no sense (these warnings came up now as numpydoc and sphinx got more strict of not accepting non existing API links).

It's usually quite useful to look at the generated docs, tons of links are unresolved: https://spectral-cube.readthedocs.io/en/latest/big_data.html

(And the rule of thumb is to use the API docs to see which namespace stuff if documented https://spectral-cube.readthedocs.io/en/latest/api.html (or, of course, one can look into the intersphinx directly))

**Comment by pllim** [comment]
```
py:obj reference target not found
```

That means you are not linking to the correct API link. You can do one of the following:

1. Find the correct API link.
2. Use double-backticks to not link it.

**Comment by keflavich** [comment]
Thanks.  Some of those make sense and are easy to fix.  Some I still find utterly boggling; I can't find any references to `reshape` anywhere... anyway, I'll try to track them down now

**Comment by pllim** [comment]
If you inherit docstring or doing something funky like that, you need to trace it back to where it is actually defined. A recursive grep has helped me in the past.

**Comment by keflavich** [comment]
I have the feeling that the API docs are searching for methods, finding them, then not finding the references to those same objects?

I'm... also... still not getting it.
```
/Users/adam/repos/spectral-cube/docs/big_data.rst:45: WARNING: py:meth reference target not found: spectral_cube.SpectralCube.filled_data
/Users/adam/repos/spectral-cube/docs/big_data.rst:45: WARNING: py:meth reference target not found: spectral_cube.SpectralCube.unmasked_data
/Users/adam/repos/spectral-cube/docs/big_data.rst:45: WARNING: py:meth reference target not found: spectral_cube.SpectralCube.world
/Users/adam/repos/spectral-cube/docs/big_data.rst:59: WARNING: py:meth reference target not found: spectral_cube.SpectralCube.filled_data
/Users/adam/repos/spectral-cube/docs/big_data.rst:59: WARNING: py:meth reference target not found: spectral_cube.SpectralCube.unmasked_data
/Users/adam/repos/spectral-cube/docs/spectral_extraction.rst:51: WARNING: py:meth reference target not found: spectral_cube.BaseSpectralCube.subcube_from_ds9region
/Users/adam/repos/spectral-cube/docs/spectral_extraction.rst:58: WARNING: py:meth reference target not found: spectral_cube.BaseSpectralCube.subcube_from_crtfregion
/Users/adam/repos/spectral-cube/docs/spectral_extraction.rst:65: WARNING: py:meth reference target not found: spectral_cube.BaseSpectralCube.subcube_from_regions
```
these are the ones I'm still tracking down (note to self)

**Comment by bsipocz** [comment]
try to drop the `:meth` from the beginning, they might not listed as methods in the intersphinx mapping

**Comment by keflavich** [comment]
😭

**Comment by keflavich** [comment]
There are very deep problems associated w/automodapi in which properties are not being autodoc'd.  I'm declaring our docs "broken but green" until we come up with a solution; real functionality cannot be held back by these failures any longer.

**Pull request merged**
