### PR TITLE
WIP: start testing CASA I/O on Travis

### PR DESCRIPTION
**Pull request by astrofrog**
I have to stop for now, but here's a status update so far: the testing is working but it turns out python-casacore has quite a different API than taskinit, so in fact I had to write some new conversion code, which kind of defies the point of trying to test the original code, so this still doesn't test the original CASA code. However, this could still be useful if people want to use python-casacore.

Remaining TODOs:

* [ ] Fix order of coordinates (at the moment stokes and frequency are swapped, not sure why - could be a bug so opened https://github.com/casacore/python-casacore/issues/129)
* [ ] Fix initialization of StokesSpectralCube in ``casa_image.py`` (currently broken)
* [ ] Remove debug print statements
* [ ] Remove ``DEBUG`` commit

I don't have any more time to work on this for now, so others should feel free to take over, otherwise I'll try and get back to it in a couple of weeks.

**NOTE**: this only works with Python 2.7, as Python 3.x segfaults: https://github.com/casacore/python-casacore/issues/128

### CODE REVIEW

**Comment by astrofrog** [comment]
I have to stop for now, but here's a status update so far: the testing is working but it turns out python-casacore has quite a different API than taskinit, so in fact I had to write some new conversion code, which kind of defies the point of trying to test the original code, so this still doesn't test the original CASA code. However, this could still be useful if people want to use python-casacore.

Remaining TODOs:

* [ ] Fix order of coordinates (at the moment stokes and frequency are swapped, not sure why)
* [ ] Fix initialization of StokesSpectralCube in ``casa_image.py`` (currently broken)
* [ ] Remove ``DEBUG`` commit

I don't have any more time to work on this for now, so others should feel free to take over, otherwise I'll try and get back to it in a couple of weeks.

**Comment by keflavich** [comment]
Is another `todo` here to revert travis to performing all the py3 tests plus a py2 test with CASA?  Otherwise it appears that the travis grid will exclude the existing tests?

**Comment by astrofrog** [comment]
@keflavich - yep, the DEBUG commit is temporary :)

**Comment by keflavich** [comment]
We can resuscitate this with CASA6 now

**Comment by astrofrog** [comment]
I'm going to close this since we now have testing against casatools & casatasks in Travis.

**Pull request closed without merging**
