### PR TITLE
Return spectral axis units in OneDSpectrum

### PR DESCRIPTION
**Pull request by e-koch**
No units were being returned with the spectral axis in OneDSpectrum.

### CODE REVIEW

**Comment by keflavich** [comment]
:+1:, but we should also include conversion to the `OneDSpectrum`'s unit (as we do with `SpectralCube`)

**Comment by keflavich** [comment]
e.g., https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/spectral_cube.py#L1853

**Comment by e-koch** [comment]
@keflavich  - So `__new__` would accept a `spectral_unit` argument?

**Comment by e-koch** [comment]
I suppose a `with_spectral_unit` method should also be added.

**Comment by e-koch** [comment]
Adding `with_spectral_unit` isn't as trivial as I had hoped. The new WCS from `spectral_axis.convert_spectral_axis` reverts to the original units when `newwcs.wcs.set()` is called. @keflavich - Any idea why that is happening?

**Comment by keflavich** [comment]
@e-koch yes.  WCS has a method... forget the name, but something like "fixunits"... that is called every time any manipulation is made of the WCS, and it automatically converts to a specific set of units (deg, deg, [m/s, hz, m]).  This is why we change the units on outputting them in https://github.com/radio-astro-tools/spectral-cube/blob/master/spectral_cube/spectral_cube.py#L1853 rather than changing the underlying WCS.  So, any tracking of units has to happen at the class level, not at the WCS level.  This is a fundamental limitation of the wcslib library, so it's not something that can be worked around even in astropy.

**Comment by keflavich** [comment]
This looks pretty good to me now, but there is a lot of duplicated code between `OneDSpectrum` and `SpectralCube` now (only one function, but a lot of lines).  Is this a case where we want some parent class to inherit the function from?  Is that called a mixin class?  @astrofrog, you might know the terminology better than I do.

**Comment by e-koch** [comment]
I think this is going to need a `_new_cube_with` to method as well (or add this to `with_spectral_unit`). The WCS unit conversion is still an issue here. I'm probably going to be delayed with adding changes until ~ Monday.

I think a parent class with common functionality would be a good idea. In another branch, I've added `world` and `spatial_coordinate_map` functionality to `Projection` so you can extract regions based on world coordinates (like `subcube`). The vast majority of the additions are duplicates from `SpectralCube`.

We could split `with_spectral_unit` and maybe `spectral_axis` functionality into its own class, and a generalized version of `world`, `spatial_coordinate_map`, `world_extrema`, etc... into another. Maybe?

**Comment by keflavich** [comment]
@e-koch that sounds like a plan, and perhaps a good idea for a half-day sprint next week

**Comment by keflavich** [comment]
merged manually with a rebase... ugly weird history here; I tried PRing onto e-koch's branch then rebased onto master and that lead to a royal mess, so I just dealt with it offline

**Pull request closed without merging**
