### PR TITLE
Stokes I empty mask

### PR DESCRIPTION
**Pull request by e-koch**
Found a small bug in checking the Stokes I mask from #607.

### CODE REVIEW

**Comment by e-koch** [comment]
I'm unsure how common it is for the casa image to have no mask. The bug came up when reading in some temporary images that are forced to have no mask.

**Comment by e-koch** [comment]
@astrofrog -- I've had trouble making a test for this. `ia.fromfits` and force creating an empty image (`ia.newimagefromshape`) both automatically create a mask. It seems like this won't be a common case.

**Comment by astrofrog** [comment]
@e-koch - the easiest way might be to generate a dataset then remove the mask in the test before trying to parse it?

**Comment by astrofrog** [comment]
I cherry-picked the commit here into #609 and added a regression test

**Pull request closed without merging**
