### PR TITLE
Find the real CASA beamtable

### PR DESCRIPTION
**Pull request by AlecThomson**
A simple fix for #878

### CODE REVIEW

**Review by keflavich — APPROVED** [review]
This is a fine change to make the HDU identification more specific.  @e-koch @astrofrog any further thoughts?

**Comment by AlecThomson** [comment]
Hi @keflavich, any movement on this PR? I have some downstream packages that would really appreciate this fix being in place

**Comment by e-koch** [comment]
@AlecThomson I think I've fixed the tests. I'll merge this if none of the test failures are related to this PR.

Our tests with beam tables also weren't using the extension name.

**Comment by e-koch** [comment]
thanks @AlecThomson !

**Comment by AlecThomson** [comment]
Thanks all!

**Pull request merged**
