### PR TITLE
Minor changes in docs

### PR DESCRIPTION
**Pull request by migueldvb**

### CODE REVIEW

**Comment by keflavich** [comment]
Neat, thanks for this fix!  I suppose we didn't know how to do this concisely when we wrote the docs.

**Comment by keflavich** [comment]
There are two failures in python2, which I suspect may be because python2 is tied to an older astropy version that doesn't handle WCS as well.... but I'm not really sure.

**Comment by keflavich** [comment]
If https://github.com/radio-astro-tools/spectral-cube/pull/490 passes, I recommend merging that into this one; I hope it will resolve the problem.  My local tests on py2.7 w/np1.13 passed using your modifications.

**Comment by migueldvb** [comment]
I have merged #490 and got one error. It seemed to be a change in the indentation of the output from the `print(cube)` command in http://spectral-cube.readthedocs.io/en/latest/index.html#quick-start.  I hope this build job will pass now.

**Pull request merged**
